import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
let server,browser;
const origin='http://127.0.0.1:4179';
const errors=[];
before(async()=>{server=spawn(process.execPath,['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4179','--strictPort']);for(let n=0;n<100;n++){try{if((await fetch(origin)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}browser=await chromium.launch({executablePath:process.env.CHROME_BIN,headless:true});});
after(async()=>{await browser?.close();server?.kill();});
async function setup(width,query){const context=await browser.newContext({viewport:{width,height:844},reducedMotion:'reduce'});await context.addInitScript(()=>{try{localStorage.setItem('milo_intro_seen_v1','1');}catch{}window.open=()=>null;});const page=await context.newPage();page.setDefaultTimeout(6000);page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+query);return{page,context};}
const state=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('milo_prototype_v1_state')));
const screen=(p,expected,id='aarav')=>p.waitForFunction(({expected,id})=>JSON.parse(localStorage.getItem('milo_prototype_v1_state'))[id==='aarav'?'sessionA':'sessionB'].screen===expected,{expected,id});
for(const width of [320,420]){
 test(`Back/Forward and arrow share history without undoing inputs (${width})`,async()=>{const{page:p,context}=await setup(width,'?screen=s1');try{await p.locator('[data-intent-id=intimate]').click();await p.locator('#miloCta-aarav').click();await screen(p,'planning_path');await p.locator('[data-planning-mode=solo]').click();await p.locator('.milo-threshold-container').click();await screen(p,'s2');assert.equal(await p.evaluate(()=>history.state.miloJourney.index),2);await p.goBack();await screen(p,'planning_path');assert.deepEqual((await state(p)).sessionA.intents,['intimate']);assert.equal((await state(p)).sessionA.planningMode,'solo');await p.goForward();await screen(p,'s2');await p.locator('#miloDeckUndo-aarav').click();await screen(p,'planning_path');await p.waitForFunction(()=>history.state.miloJourney.index===1);await p.locator('#miloPathBack').click();await screen(p,'s1');await p.waitForFunction(()=>history.state.miloJourney.index===0);await p.goForward();await screen(p,'planning_path');assert.deepEqual((await state(p)).sessionA.intents,['intimate']);}finally{await context.close();}});
 test(`itinerary, overlay Back and no plan write on dismissal (${width})`,async()=>{const{page:p,context}=await setup(width,'?golden=1&screen=s6');try{await p.locator('[data-open-night=middle-ground]').click();await screen(p,'s7');const saved=await state(p);await p.locator('[data-customise-slot="0"]').click();await p.waitForFunction(()=>history.state.miloJourney.kind==='dialog');await p.goBack();await p.locator('dialog').waitFor({state:'detached'});assert.deepEqual(await state(p),saved);await p.goBack();await screen(p,'s6');await p.goForward();await screen(p,'s7');assert.equal(await p.locator('dialog').count(),0);await p.locator('[data-customise-slot="0"]').click();await p.locator('[data-close]').first().click();await p.waitForFunction(()=>history.state.miloJourney.kind==='route');await p.goBack();await screen(p,'s6');}finally{await context.close();}});
 test(`solo timing Back keeps saved draft (${width})`,async()=>{const{page:p,context}=await setup(width,'?golden=1&screen=planning_path_review');try{await p.locator('[data-planning-mode=solo]').click();await screen(p,'s6');await p.locator('[data-open-night=middle-ground]').click();await p.locator('#miloSoloSave').click();await p.locator('#miloSoloTimingBack').waitFor();await p.goBack();await p.locator('#miloSoloSave').waitFor();assert.equal((await state(p)).sessionA.savedSoloNightId,'middle-ground');assert.equal((await state(p)).sessionA.soloTimingStep,null);await p.goForward();await p.locator('#miloSoloTimingBack').waitFor();}finally{await context.close();}});
 test(`partner browser Back retains review guard (${width})`,async()=>{const{page:p,context}=await setup(width,'?golden=1&as=sneha&screen=s2');try{await p.evaluate(()=>{const k='milo_prototype_v1_state',s=JSON.parse(localStorage.getItem(k));s.sessionB.currentCardIndex=0;s.sessionB.reactions=[];localStorage.setItem(k,JSON.stringify(s));});await p.goto(origin+'/?as=sneha');for(let i=0;i<8;i++){await p.locator('#btnMaybe-sneha').click();await p.waitForFunction(i=>JSON.parse(localStorage.getItem('milo_prototype_v1_state')).sessionB.currentCardIndex===i+1,i);}await screen(p,'s5','sneha');const saved=await state(p);await p.goBack();await p.locator('.milo-overlap-back-dialog').waitFor();await p.locator('[data-back-cancel]').click();assert.deepEqual(await state(p),saved);await p.goBack();await p.locator('.milo-overlap-back-dialog').waitFor();await p.locator('[data-back-confirm]').click();await screen(p,'s1','sneha');assert.deepEqual((await state(p)).sessionB.reactions,saved.sessionB.reactions);}finally{await context.close();}});
}
test('Back during threshold cancels its pending advance',async()=>{const{page:p,context}=await setup(420,'?screen=s1');try{await p.locator('[data-intent-id=intimate]').click();await p.locator('#miloCta-aarav').click();await p.locator('[data-planning-mode=together]').click();await p.locator('.milo-threshold-container').waitFor();await p.goBack();await screen(p,'planning_path');await p.waitForTimeout(2000);await screen(p,'planning_path');}finally{await context.close();}});
test('refresh keeps current saved state; root Back is not trapped',async()=>{const{page:p,context}=await setup(420,'?screen=s1');try{await p.locator('[data-intent-id=intimate]').click();await p.locator('#miloCta-aarav').click();await p.reload();await screen(p,'planning_path');assert.deepEqual((await state(p)).sessionA.intents,['intimate']);assert.equal(await p.evaluate(()=>history.state.miloJourney.index),0);await p.goto('about:blank');await p.goBack();await p.locator('[data-planning-mode=solo]').waitFor();}finally{await context.close();}});
for (const width of [320,420]) for (const actor of ['aarav','sneha']) {
 test(`deck browser Back undoes one recorded vote and exits only on first card (${actor},${width})`,async()=>{const{page:p,context}=await setup(width,'?screen=s2'+(actor==='sneha'?'&as=sneha':''));try{const key=actor==='sneha'?'sessionB':'sessionA';const original=await state(p);for(let i=0;i<2;i++){await p.locator(`#btnMaybe-${actor}`).click();await p.waitForFunction(({key,n})=>JSON.parse(localStorage.getItem('milo_prototype_v1_state'))[key].currentCardIndex===n,{key,n:i+1});}await p.goBack();await p.waitForFunction(key=>JSON.parse(localStorage.getItem('milo_prototype_v1_state'))[key].currentCardIndex===1,key);let saved=await state(p);assert.equal(saved[key].screen,'s2');assert.equal(saved[key].reactions.length,1);assert.deepEqual(saved.shared,original.shared);await p.goBack();await p.waitForFunction(key=>JSON.parse(localStorage.getItem('milo_prototype_v1_state'))[key].currentCardIndex===0,key);saved=await state(p);assert.equal(saved[key].reactions.length,0);assert.equal(saved[key].screen,'s2');await p.goBack();await screen(p,actor==='sneha'?'s1':'planning_path',actor);await p.goForward();await screen(p,'s2',actor);assert.equal((await state(p))[key].reactions.length,0);}finally{await context.close();}});
}
test('deck Back cancels pending reaction before undoing last saved vote',async()=>{const{page:p,context}=await setup(420,'?screen=s2');try{await p.locator('#btnMaybe-aarav').click();await p.waitForFunction(()=>JSON.parse(localStorage.getItem('milo_prototype_v1_state')).sessionA.currentCardIndex===1);await p.locator('#btnIntoIt-aarav').click();await p.goBack();await p.waitForFunction(()=>JSON.parse(localStorage.getItem('milo_prototype_v1_state')).sessionA.currentCardIndex===0);await p.waitForTimeout(400);const s=await state(p);assert.equal(s.sessionA.screen,'s2');assert.deepEqual(s.sessionA.reactions,[]);}finally{await context.close();}});
test('no uncaught errors across history flows',()=>assert.deepEqual(errors,[]));
